server:
  port: 12276

info:
  app:
    name: '@project.name@'
    version: '@project.version@'

spring:
  application:
    name: exam
mybatis:
  configuration:
    map-underscore-to-camel-case: true
mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      table-prefix: t_

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
