server:
  port: 12276

info:
  app:
    name: @project.name@
    version: @project.version@

spring:
  application:
    name: exam
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://8.135.66.238:3306/exam
    username: root
    password: Abcd1234
    platform: mariadb
mybatis:
  configuration:
    map-underscore-to-camel-case: true
mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      table-prefix: t_

management:
  endpoint:
    health:
      show-details: always

#eureka:
#  client:
#    register-with-eureka: false
#    fetch-registry: false
