spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://mariadb:3306/exam
    username: root
    password: Abcd1234
    platform: mariadb
  redis:
    host: redis
    password: abc123

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/
