server:
  port: 12276

spring:
  application:
    name: exam
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mysql://8.135.66.238:3306/exam
    username: root
    password: Abcd1234
    platform: mariadb
mybatis:
  configuration:
    map-underscore-to-camel-case: true
mybatis-plus:
  global-config:
    db-config:
      table-prefix: t_

#eureka:
#  client:
#    register-with-eureka: false
#    fetch-registry: false
