server:
  port: 8762

spring:
  application:
    name: admin

eureka:
  client:
    serviceUrl:
      defaultZone: http://8.135.66.238:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
