server:
  port: 12277

info:
  app:
    name: '@project.name@'
    version: '@project.version@'

spring:
  application:
    name: topic
mybatis:
  configuration:
    map-underscore-to-camel-case: true
mybatis-plus:
  global-config:
    db-config:
      table-prefix: t_

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
