spring:
  application:
    name: pure

server:
  port: 8901

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8888/eureka/

security:
  oauth2:
    client:
      client-id: rz
      client-secret: abc123
      access-token-uri: http://localhost:8080/oauth/token
      user-authorization-uri: http://localhost:8080/oauth/authorize
    authorization:
      check-token-access: http://localhost:8080/oauth/check_token
    resource:
      token-info-uri: http://localhost:8080/oauth/check_token
      user-info-uri: http://localhost:8080/user
