spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.111.244.130:3306/rz
    username: root
    password: abc123

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8888/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
