spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mysql://localhost:3306/demo
    username: root
    password: Abcd1234
    platform: mariadb
    initialization-mode: always

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
