server:
  port: 9999

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        # exam服务
        - id: completions
          uri: lb://exam
          predicates:
            - Path=/completions/**
        - id: choices
          uri: lb://exam
          predicates:
            - Path=/choices/**
        - id: exams
          uri: lb://exam
          predicates:
            - Path=/exams/**
        - id: practice
          uri: lb://exam
          predicates:
            - Path=/practice/**
        # topic服务
        - id: topics
          uri: lb://topic
          predicates:
            - Path=/topics/**
        - id: catalogs
          uri: lb://topic
          predicates:
            - Path=/catalogs/**

eureka:
  client:
    # 每隔5秒刷新服务信息
    registry-fetch-interval-seconds: 5

management:
  endpoints:
    web:
      exposure:
        include: '*'
