server:
  port: 9999

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: exam
          uri: lb://exam
          predicates:
            - Path=/completions/**,/choices/**,/exams/**,/practice/**
        - id: topic
          uri: lb://topic
          predicates:
            - Path=/topics/**,/catalogs/**

eureka:
  client:
    # 每隔5秒刷新服务信息
    registry-fetch-interval-seconds: 5

management:
  endpoints:
    web:
      exposure:
        include: '*'
