server:
  port: 9999

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        # exam服务
        - id: completions
          uri: lb://exam
          predicates:
            - Path=/completions/**
        - id: exams
          uri: lb://exam
          predicates:
            - Path=/exams/**
        - id: practice
          uri: lb://exam
          predicates:
            - Path=/practice/**
        # topic服务
        - id: topics
          uri: lb://topic
          predicates:
            - Path=/topics/**
        - id: catalogs
          uri: lb://topic
          predicates:
            - Path=/catalogs/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://8.135.66.238:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: '*'
