spring:
  cloud:
    gateway:
      routes:
      - id: completions
        uri: lb:exam
        predicates:
        - Path=/completions/**
#        filters:
#        - StripPrefix=1
      - id: exams
        uri: lb:exam
        predicates:
        - Path=/exams/**
      - id: topics
        uri: lb:topic
        predicates:
        - Path=/topics/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://8.135.66.238:8761/eureka/
